name: <plugin_name>
main: io.github.gilden00.<plugin_name>.<main_class>
description: <Description>
version: <Version>

authors: [ Gilden00 ]
depend: [  ]
softdepend: [  ]
website: http://gilden00.github.io/<plugin_name>

commands:
   basic:
      description: This is a demo command.
      usage: /basic
      permission: TestPlugin.basic
      permission-message: You don't have permission to use TestPlugin.basic
   basic2:
      description: This is a demo command that can only be issued by the player.
      usage: /basic2
      permission: TestPlugin.basic2
      permission-message: You don't have permission to use TestPlugin.basic2